### ISSUE TITLE
Support for Next DNS

### ISSUE THREAD

**Issue by SeriousHoax** [bitbeans/SimpleDnsCrypt#417] opened 2019-07-10 19:15 UTC
Is it possible anyhow to add support for Next DNS? https://nextdns.io 
I know it's actually different from other DNS service but asking just to be sure.

**Comment by jedisct1** [comment] 2019-07-10 20:23
You can already use NextDNS anonymously. Just choose "NextDNS" in the list.

If you registered filtering rules, NextDNS gives you a DNS Stamp for dnscrypt-proxy.

So your ticket looks like a duplicate of https://github.com/bitbeans/SimpleDnsCrypt/issues/393

**Comment by SeriousHoax** [comment] 2019-07-11 07:43
I see, thanks. I finally found nextdns (DoH) on the list. But how do I use my DNS Stamp with SimpleDnsCrypt? I'm actually new to this so any instruction or maybe a link where the method is described would be helpful.

**Comment by graphixillusion** [comment] 2019-07-21 09:27
@SeriousHoax take a look to the official wiki:

https://github.com/jedisct1/dnscrypt-proxy/wiki/Configuration

**Comment by SeriousHoax** [comment] 2019-07-23 09:41
> 
> 
> @SeriousHoax take a look to the official wiki:
> 
> https://github.com/jedisct1/dnscrypt-proxy/wiki/Configuration
> 
> On my system i needed to use **"** instead of **'** so the configuration will be like this
> 
> `server_names = ["nextdns-custom-name", "second_dns_reslover"]`
> `[static."nextdns-custom-name"]`
> `stamp = "sdns_entry_address"`

Thanks a lot. With your comment and via the help of this guide I managed to do it.  https://cleanbrowsing.org/guides/how-to-configure-cleanbrowsing-and-dnscrypt

**Closed** 2019-07-23 09:41 UTC
